In [9]:
import torch
a = torch.tensor([[3,4,5],[3,4,5],[3,4,5]], dtype=torch.float64)
b = torch.tensor([[6,7,8],[3,4,5],[3,4,5]], dtype=torch.float64)
a+b

tensor([[ 9., 11., 13.],
        [ 6.,  8., 10.],
        [ 6.,  8., 10.]], dtype=torch.float64)

In [10]:
torch.add(a,b) 

tensor([[ 9., 11., 13.],
        [ 6.,  8., 10.],
        [ 6.,  8., 10.]], dtype=torch.float64)

In [18]:
c = torch.zeros(3,3)

In [19]:
c

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
torch.add(a,b, out=c)

tensor([[ 9., 11., 13.],
        [ 6.,  8., 10.],
        [ 6.,  8., 10.]])

In [21]:
n = torch.add(a,b)

In [22]:
n

tensor([[ 9., 11., 13.],
        [ 6.,  8., 10.],
        [ 6.,  8., 10.]], dtype=torch.float64)

In [23]:
torch.add(a,b).sum()

tensor(81., dtype=torch.float64)

Dot products and multiple operation


In [25]:
x = torch.tensor([3,4,5], dtype=torch.float64)
y = torch.tensor([6,7,8], dtype=torch.float64)

In [26]:
x.mul(y)

tensor([18., 28., 40.], dtype=torch.float64)

In [27]:
x.dot(y)

tensor(86., dtype=torch.float64)